### ISSUE TITLE
Support Google material symbols for icons for webfonts

### ISSUE THREAD

**Issue by andyjamesn** [oruga-ui/oruga#359]
I am referring to these material font icons

[ Material Symbol Icons](https://fonts.google.com/icons)

### Description

Use material symbols for icons for normal icons or icons in buttons and inputs

### Why Oruga need this feature

The google material symbols are the latest release to material design and offer extremely flexible icons/symbols that are really easy to use

You can read about the release here:
[Introducing Material Symbols](https://material.io/blog/introducing-symbols)

Using the webfont makes it easy to include the icons in any environment easily.

Including the entire materialdesignicons.css adds 374kb to the build where as using Google fonts the icon font weighs in at only 42KB for the woff2 file as per this recource

https://developers.google.com/fonts/docs/material_icons

Currently this is not possible due to the way the font name is added and its different from other font icons

Instead of `<i class="iconname"></i>`

It is like this

```html
<span class="material-icons">
close
</span>
```

The only thing needed to get this to work is to include the css eg:

```css
@font-face {
    font-family: 'Material Icons';
    font-style: normal;
    font-weight: 400;
    src: url(https://fonts.gstatic.com/s/materialicons/v125/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2)
        format('woff2');
}
```
