### ISSUE TITLE
Oruga radio button color can't be overridden with CSS variable

### ISSUE THREAD

**Issue by MattiasMartens** [oruga-ui/oruga#380]
# Description

The Oruga radio button's colour is controlled with CSS variable `--oruga-radio-active-background-color`. However, changing this variable globally does not change the colour of the button.

Here's why:

```css
.o-radio__check--checked {
  background-image: url(...)
}
```

The SVG in the URL:

```svg
<svg width='100%' height='100%' viewBox='0 0 100 100' version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' xml:space='preserve' xmlns:serif='http://www.serif.com/' style='fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;'><g transform='matrix(4.38544,0,0,4.38544,-94.4336,-58.9876)'><path d='M32.935,13.679C39.102,13.679 44.108,18.685 44.108,24.852C44.108,31.019 39.102,36.025 32.935,36.025C26.768,36.025 21.761,31.019 21.761,24.852C21.761,18.685 26.768,13.679 32.935,13.679ZM32.798,17.05C37.105,17.05 40.601,20.546 40.601,24.852C40.601,29.158 37.105,32.655 32.798,32.655C28.492,32.655 24.996,29.158 24.996,24.852C24.996,20.546 28.492,17.05 32.798,17.05Z' style='fill:var(--oruga-radio-active-background-color, #445e00);'/><circle cx='32.84' cy='24.8' r='7.9' style='fill:transparent;'/></g></svg>
```

As you can see, the fill colour draws from the variable as expected; but because it's a background-image CSS property, the SVG being rendered is not part of the DOM and does not have access to the variable.

This StackOverflow question explains the problem fully: https://stackoverflow.com/questions/51395179/svg-fill-with-css-variables

Users there have also offered a few fixes:

## Fix 1.

Use mask-image property instead of background-image property:

```css
  #app .o-radio__check {
    background: var(--oruga-radio-active-background-color, #445e00);
    background-image: none;
    mask-image: url("data:image/svg+xml,%3Csvg%20width%3D'100%25'%20height%3D'100%25'%20viewBox%3D'0%200%20100%20100'%20version%3D'1.1'%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20xmlns%3Axlink%3D'http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink'%20xml%3Aspace%3D'preserve'%20xmlns%3Aserif%3D'http%3A%2F%2Fwww.serif.com%2F'%20style%3D'fill-rule%3Aevenodd%3Bclip-rule%3Aevenodd%3Bstroke-linejoin%3Around%3Bstroke-miterlimit%3A2%3B'%3E%3Cg%20transform%3D'matrix(10.1032%2C0%2C0%2C10.1032%2C-255.068%2C-313.298)'%3E%3Ccircle%20cx%3D'30.195'%20cy%3D'35.959'%20r%3D'4.85'%2F%3E%3C%2Fg%3E%3C%2Fsvg%3E");
  }
  
  #app .o-radio__check--checked {
    background: var(--oruga-radio-active-background-color, #445e00);
    background-image: none;
    mask-image: url("data:image/svg+xml,%3Csvg%20width%3D'100%25'%20height%3D'100%25'%20viewBox%3D'0%200%20100%20100'%20version%3D'1.1'%20xmlns%3D'http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg'%20xmlns%3Axlink%3D'http%3A%2F%2Fwww.w3.org%2F1999%2Fxlink'%20xml%3Aspace%3D'preserve'%20xmlns%3Aserif%3D'http%3A%2F%2Fwww.serif.com%2F'%20style%3D'fill-rule%3Aevenodd%3Bclip-rule%3Aevenodd%3Bstroke-linejoin%3Around%3Bstroke-miterlimit%3A2%3B'%3E%3Cg%20transform%3D'matrix(4.38544%2C0%2C0%2C4.38544%2C-94.4336%2C-58.9876)'%3E%3Cpath%20d%3D'M32.935%2C13.679C39.102%2C13.679%2044.108%2C18.685%2044.108%2C24.852C44.108%2C31.019%2039.102%2C36.025%2032.935%2C36.025C26.768%2C36.025%2021.761%2C31.019%2021.761%2C24.852C21.761%2C18.685%2026.768%2C13.679%2032.935%2C13.679ZM32.798%2C17.05C37.105%2C17.05%2040.601%2C20.546%2040.601%2C24.852C40.601%2C29.158%2037.105%2C32.655%2032.798%2C32.655C28.492%2C32.655%2024.996%2C29.158%2024.996%2C24.852C24.996%2C20.546%2028.492%2C17.05%2032.798%2C17.05Z'%2F%3E%3Ccircle%20cx%3D'32.84'%20cy%3D'24.8'%20r%3D'7.9'%20style%3D'fill%3Atransparent%3B'%2F%3E%3C%2Fg%3E%3C%2Fsvg%3E");
  }
```

`mask-image` can fill with the background draw colour and so is not subject to this issue. Only drawback is that it is less supported (e.g. to work in Chrome the example needs to be polyfilled with -webkit-mask-image).

## Fix 2.

Render the SVG inline rather than with the background-image property and superimpose it on the input with absolute positioning.

## Fix 3.

A possible fallback is to grab the CSS variable in JS and programmatically inject it into the SVG during build.

**Oruga** version: @oruga-ui/oruga-next@0.5.5
**Vuejs** version: 3.2.29
**OS/Browser**: Mac/Chrome

# Expected behaviour

The CSS variable `--oruga-radio-active-background-color` can be set to control the colour of the radio button.
