### ISSUE TITLE
[Feature Request] Size of Carousel Indicator

### ISSUE THREAD

**Issue by zhaolinlau** [oruga-ui/oruga#594]
### Description

able to customize the size of carousel indicator by adding `is-small`, `is-medium`, `is-large` to `indicatorCustomSize` just like buefy

![image](https://github.com/oruga-ui/oruga/assets/68846168/41624c88-5a69-4706-817f-b76d1792f381)

### Why Oruga need this feature

easier to click, and i think for current indicator is abit small

**Comment by mlmoravek** [comment]
You could override the size by your css or use the CSS-Variables to do so.

**Comment by zhaolinlau** [comment]
> You could override the size by your css or use the CSS-Variables to do so.

any example?

**Comment by mlmoravek** [comment]
@zhaolinlau Which theme do you use? The default Oruga one?

**Comment by zhaolinlau** [comment]
> @zhaolinlau Which theme do you use? The default Oruga one?

bulma theme

**Comment by mlmoravek** [comment]
Sadyl bulma does not use CSS-Variables, but you could override the css anyway:

``` css
.carousel .carousel-indicator .indicator-item .indicator-style.is-dots {
    height: 20px;
    width: 20px;
}
```
